### ISSUE TITLE
Research ReqIF as an import/export format.

### ISSUE THREAD

**Issue by jacebrowning** [doorstop-dev/doorstop#104]
Determine if ReqIF is widely used and makes sense to support for import/export: http://www.omg.org/spec/ReqIF/

**Comment by patkan** [comment]
Hello, I have just discovered this tool.
Is this format really seldomly used? According to similar tools this format is used to import and export the requirements without loosing the metadata. This is of course covered by the available formats, but ReqIF would allegedly allow to import easily into other tools.

**Comment by jacebrowning** [comment]
Do you have a list of tools that support this format?

**Comment by patkan** [comment]
I searched for tools supporting this format, this list is probably not exhaustive:
* [Rational DOORS](https://www.ibm.com/support/knowledgecenter/en/SSYQBZ_9.6.1/com.ibm.doors.administering.doc/topics/c_aboutRIF.html)
* [Polarion ALM](https://almdemo.polarion.com/polarion/help/?topic=/com.polarion.xray.doc.user/ugDocsReqIfImportExport.html)
* [ReqView](https://www.reqview.com/doc/import-reqif-doors.html)
* [PTC Integrity](https://community.ptc.com/t5/Integrity-Questions/Not-able-to-find-ReqIf-import-option-in-Integrity-Client/td-p/80008)
* [NoMagic MagicDraw](https://www.nomagic.com/mbse/images/whitepapers/Requirements_Interchange_Format_ReqIF_Importer.pdf)
