### ISSUE TITLE
Doorstop command to add/remove properties

### ISSUE THREAD

**Issue by robertberrington** [doorstop-dev/doorstop#183]
It might be helpful to add a command to add/remove/rename a metadata property. It might be helpful if the property has data, that the command returns a `ERROR`, then it requires a `--force` command to make it happen.

```
$ doorstop DVPnR property --add tasteowner
$ doorstop DVPnR property --rename tasteowner testowner
$ doorstop DVPnR property --delete testowner
ERROR   DVPnR "testowner" contains data, use --force option to delete
$ doorstop DVPnR property --delete testowner --force
```
##

**Comment by neerdoc** [comment]
@jacebrowning Is this something that should be done?

**Comment by jacebrowning** [comment]
@neerdoc No, I don't think so. This is getting a little too close to implementing a full text editor on the command line.

The [export/import workflow](https://doorstop.readthedocs.io/en/latest/cli/interchange/) should be sufficient for making bulk changes.
