### ISSUE TITLE
Report a better error when VCS metadata is missing

### ISSUE THREAD

**Issue by jacebrowning** [doorstop-dev/doorstop#201]
Instead of:

```
ERROR: no working copy found from: /home/foobar/
```

let the user know that Doorstop was looking for for VCS metadata and prompt them to initialize a repo.
##

**Comment by jacebrowning** [comment]
No one else has reported this so I think we can close.

**Comment by pintert3** [comment]
I know this was closed, but it's a real problem. I agree that there should be a better error, or at least some documentation on what to expect when trying to create a document for the first time. I suggest we reopen this.
