### ISSUE TITLE
Interest in getting CII Badge?

### ISSUE THREAD

**Issue by devcurmudgeon** [doorstop-dev/doorstop#242]
Core Infrastructure Initiative has a [free badging programme](https://www.coreinfrastructure.org/programs/badge-program) for generic best-practices, including documentation, release processes, ci etc. 

If folks agree this is worth doing, I'd be willing to start the form-filling, since I think this activity would help me to find out more about the doorstop project.

**Comment by jacebrowning** [comment]
I don't see any downsides to doing this. Doorstop already incorporates most of the best practices they identify.

**Comment by devcurmudgeon** [comment]
So I've answered as much as I can, at ![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/754/badge)

Key remaining questions are about how doorstop project deals with security/vulnerabilities - I can't find any information about this in the documentation, and am not clear if the project has 'at least one primary developer who knows how to design secure software'.

Also when i run pylint, I see lots of warnings - could that be a config error on my part? if the warnings are real, I could maybe start offering patches...

**Comment by jacebrowning** [comment]
> if the project has 'at least one primary developer who knows how to design secure software'

I'm not sure how to answer that. Much of Doorstop's security relies on that fact that it uses established systems to store data (version control), and doesn't roll its own solution.

> I see lots of warnings

I will deal with the pylint warnings as part of https://github.com/jacebrowning/doorstop/issues/241. I've adopted new standards in my other projects that I'd like to apply to this project.

**Comment by devcurmudgeon** [comment]
> Much of Doorstop's security relies on that fact that it uses established systems to store data (version control), and doesn't roll its own solution.

If you are self-certifying that you believe you know how to design secure software, that's a start. CII would like to see explicit instructions to users on how to report vulnerabilities if they are detected.

FWIW when I asked about potential vulnerabilities elsewhere...

15:32 < paulsherwood> is it reasonable to state that, for a standalone user app (commandline/gui) that operates on yaml/text files, designing for security/vulnerabilities is n/a?
15:32 <> No
15:32 < paulsherwood> context: i'm completing cii badge application for https://github.com/jacebrowning/doorstop
15:33 < paulsherwood> DavePage: pls provide example of potential attack vector
15:33 <> paulsherwood: Malformed YAML file which breaks the parser
15:33 < paulsherwood> DavePage: ok, but so what?
15:33 <> 20GB YAML file which overflows internal buffer
15:33 <> Leading to code execution
15:34 <> It depends entirely on what you do with the YAML
15:34 <> paulsherwood: Suppose it gets used as the back end for a web service, taking untrusted files
15:34 <> If one of the fields contains executable code, then obviously there can be security problems

**Comment by jacebrowning** [comment]
> taking untrusted files

At least for this core project, Doorstop has no such capabilities and I don't intent to add any. So in a sense, I would say that I know how to avoid adding features with known potential vulnerabilities.

**Comment by devcurmudgeon** [comment]
OK, would you be happy to add instructions to users on how to report suspected vulnerabilities?

**Comment by jacebrowning** [comment]
@devcurmudgeon Please do!

**Comment by jacebrowning** [comment]
@devcurmudgeon What are the requirements for this? Can it simply be GitHub issues or does there need to be a way to report issues secretly?

**Comment by devcurmudgeon** [comment]
@jacebrowning I've completed the badge process to the best of my ability at [![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/754/badge)](https://bestpractices.coreinfrastructure.org/projects/754) 

Please could you review my answers at https://bestpractices.coreinfrastructure.org/projects/754 ?

**Comment by jacebrowning** [comment]
Looks good! I made a few changes:

> What is the human-readable name of the project?

I changed this to "Doorstop".

> It is SUGGESTED that at least one of the static analysis tools used for the static_analysis criterion include rules or approaches to look for common vulnerabilities in the analyzed language or environment.

I changed this answer to "yes". Pylint includes [many checks](https://docs.pylint.org/en/1.6.0/features.html) for language misuse and unsafe coding practices.

> It is SUGGESTED that at least one dynamic analysis tool be applied

I am not sure what is meant by "dynamic analysis tool". Aren't these automated tests?

> (Future criterion) It is SUGGESTED that the project have a reproducible build.

I changed this answer to "yes" with the recent inclusion of `pipenv` and `Pipfile.lock` to install the exact versions of all dependencies during development and test.

**Comment by devcurmudgeon** [comment]
@jacebrowning - the only thing outstanding to achieve 100% is confirming that one of the primary developers knows how to write security software and mitigate against vulnerabilities. If you are willing to confirm you (or other regular contributors) fit that bill we should complete the form.

**Comment by jacebrowning** [comment]
@devcurmudgeon I don't have experience writing security software, but I'm comfortable stating that I'm capable of mitigating against vulnerabilities.

Let's wait to see if anyone else can contribute their skills.

**Comment by jacebrowning** [comment]
Perhaps @stefanoco or @sebhub are willing to vouch for their background as well to close this out?

**Comment by sebhub** [comment]
My domain is software development for embedded systems. I know little about high level application development and in particular my Python skills are quite weak. I don't think I am competent enough to do a security audit of Doorstop.

**Comment by stefanoco** [comment]
I'm trying to understand the requirements for informed and competent contributors, and I'm perhaps not the right person unfortunately. While having knowledge about Python and Security, I can't be considered an expert on both fields. If you think that having _good knowledge_ is an option then we can go this way.

**Comment by kayoub5** [comment]
I would recommend using https://sonarcloud.io/about easy to setup and free for open source.

**Comment by jacebrowning** [comment]
I think we can consider the 97% CII score good enough for now.
