### ISSUE TITLE
Doorstop and aviation industry?

### ISSUE THREAD

**Issue by crtg** [doorstop-dev/doorstop#309]
Hi there,

Is there somebody using Doorstop to handle the requirements in small projects according to ARP4575, DO-178C or DO-254 standards?

**Comment by kannode** [comment]
@crtg I was investigating doorstop for do178c. Did you choose door stop or settle on something else?

**Comment by TingForGitHub** [comment]
we are investigate Doorstop for ECSS-E-ST-40C

[](https://www.mail-archive.com/devel@rtems.org/msg18523.html)

[](https://www.mail-archive.com/devel@rtems.org/msg18529.html)

**Comment by sebhub** [comment]
Maybe a section could be added to the documentation where users can add there experience with projects using Doorstop and lessons learnt.

**Comment by jacebrowning** [comment]
Yeah, I'm not quite sure what folks are looking for.

We could also create a wiki page: https://github.com/jacebrowning/doorstop/wiki

**Comment by sevendays** [comment]
For my experience doorstop can be a brick of the wall, together with git and custom scripts.

* doorstop provides requirement management and arguments for traceability, but you usually have to use custom fields to add more data (e.g. "is_safety", "asil_grade")
* those custom fields are not included when calculating the revision, so you need your own methods to review and validate those fields
* you have to provide arguments for software tool confidence level in all safety-related applications
* my tip would be to export to CSV and write scripts using CSV as input, as most requirement management tools can export requirements in a tabular format, and your script could have a longer life than the single project.

**Comment by sebhub** [comment]
You can include now [custom fields in the fingerprint](https://github.com/jacebrowning/doorstop/blob/develop/docs/reference/items.md#extended-reviewed-attributes).
