### ISSUE TITLE
Consider adding an optional 'head' attribute to items.

### ISSUE THREAD

**Issue by jacebrowning** [doorstop-dev/doorstop#31]
The  `head` attribute would be used for publishing headers on **every** Item such as:

```
1.0 Requirements

1.1 REQ001 Start Up

The product shall start up...

1.2 REQ002 Shutdown

The product shall shut down...

1.3 REQ003

The product shall also...
```

Attribute could be called:
- `Item.head`
- `Item.heading`
- `Item.header`

Consider aliasing `Item.text` as `Item.body`.
##

**Comment by rickeywang** [comment]
How would one go about implementing this? Would also like the links to show the heading. 

Instead of a series of cryptic links like `Parent links: REQ-007, REQ-003` , it makes more sense to have a readable description with it. Like `Parent links: REQ-007 Safe Shut Down, REQ-003 Voltage Supply`

**Comment by jacebrowning** [comment]
I haven't thought about the implementation for this in some time, but I would start by looking at how other attributes are managed in the `Item` class.

Once such an attribute is available on items, a modification would be needed in the `publisher` module to include the heading alongside `item.uid` .

**Comment by neerdoc** [comment]
I believe this is already implemented.
