### ISSUE TITLE
Published markdown has links to HTML files instead of markdown files

### ISSUE THREAD

**Issue by Korijn** [doorstop-dev/doorstop#314]
Running `doorstop publish -m all ./output` generates markdown files that contain links to HTML files rather than markdown files:

`*Child links:* [TST002](TST.html#TST002)`

Probably a minor issue, might open a PR myself later.

**Comment by joeroca** [comment]
I'm still facing the same problem. So far any changes? Thanks in advance ;)

**Comment by Korijn** [comment]
We wrote our own publisher based on the python API.
