### ISSUE TITLE
Last heading can be lost from exported html sidebar

### ISSUE THREAD

**Issue by michaelnt** [doorstop-dev/doorstop#373]
The last entry (4.1) in the sidebar on the left isn't displayed. It is generated so some kind of css\js problem

![image](https://user-images.githubusercontent.com/265155/61501178-27ed6980-a9c6-11e9-9e92-b137f1257eb8.png)

**Comment by sebhub** [comment]
I am not sure if this is a bug or a feature. I see the subsections only in case a section is selected in the table of contents. This is true for all subsections, not only the last one.

**Comment by neerdoc** [comment]
I believe this is as intended.
