### ISSUE TITLE
Expected behavior or bug: table of contents of the HTML file is printed in markdown format?

### ISSUE THREAD

**Issue by stanislaw** [doorstop-dev/doorstop#378]
Looking at the `test_lines_html_document_linkify`, it appears that the `publish_lines` method produces the HTML file with a TOC in the markdown format and this looks rather confusing.

This is the file that is checked by this test: `doorstop/core/tests/files/published.html`.

I guess the expected behavior will be to transform this:

```
* [1.2.3 REQ001](#REQ001)
  * [1.4 REQ003](#REQ003)
  * [1.6 REQ004](#REQ004)
  * [2.1 Plantuml](#REQ002)
  * [2.1 REQ2-001](#REQ2-001)
```

into the proper HTML links with anchors.

If this gets confirmed to be a bug, I or anyone else could send a patch.

**Comment by neerdoc** [comment]
I agree that this is a bug.
