### ISSUE TITLE
Document Level Headers/Descriptions

### ISSUE THREAD

**Issue by NouberNou** [doorstop-dev/doorstop#418]
Is there any interest in adding document level headers/descriptions?

It feels awkward/cluttered having something generically describing the intent of a document be captured in a requirement item.

**Comment by jacebrowning** [comment]
I'm in favor of this as long as there is a way to roundtrip this information through all export/import formats.

Another option is to only inject this information when publishing: https://github.com/doorstop-dev/doorstop/issues/166

**Comment by NouberNou** [comment]
Yea I have to think on this more, something like #166 is probably more suitable for now.
