### ISSUE TITLE
Add mailing list?

### ISSUE THREAD

**Issue by sebhub** [doorstop-dev/doorstop#422]
A mailing list for this project would be nice. Doing all communication through Github issues is a bit awkward. One option would be to add a Google group:

https://groups.google.com/forum/#!overview

**Comment by NouberNou** [comment]
I actually was just coming on here to figure out how to best get in contact with the Doorstop developers specifically, but GitHub isn't the best platform for what I want to talk about.

On that note, if @jacebrowning and others would be interested I have a project that I've been working on the last month or so that heavily involves Doorstop but I am not ready to show off publicly yet. Not sure what the best place to have a conversation about this is though because of that.

**Comment by jacebrowning** [comment]
@sebhub I can't commit to keeping up with a mailing list, but feel free to create one if you'd find that helpful to communicate with others.

**Comment by devcurmudgeon** [comment]
I think a list would be a good idea. 
As an alternative to the google approach, we have an existing old-school [mailman server](https://lists.trustable.io/cgi-bin/mailman/listinfo) that already hosts a couple of projects.  I'd be happy to create a doorstop list there if that would help.

**Comment by NouberNou** [comment]
A public Slack using slackin maybe? https://github.com/rauchg/slackin

A mailing list is probably a bit more hands off though than a Slack.

**Comment by jacebrowning** [comment]
@NouberNou FYI, `slackin` is no longer required to achieve public signup as Slack now lets you generate a permanent signup link.

I'll also remind folks that there is a Gitter room as mentioned in the README: https://gitter.im/doorstop-dev/community

**Comment by NouberNou** [comment]
@jacebrowning Ah, that is good to know! Thank you.

**Comment by MartyLake** [comment]
FWIW I prefer "slow" ways of communication that enables threads and
asynchronousity. I've observed that it helps people construct better
arguments and answer to the topic, sometimes with some delay that's true.

GitHub issues is one, mail is very similar to it TBH, I am not sure I
understand what is the problem with GitHub issues.

Best,

**Comment by stanislaw** [comment]
> FWIW I prefer "slow" ways of communication that enables threads and
asynchronousity. I've observed that it helps people construct better
arguments and answer to the topic, sometimes with some delay that's true.

Fully agree. Please see the connected argument below.

> GitHub issues is one, mail is very similar to it TBH, I am not sure I
understand what is the problem with GitHub issues.

GitHub issues has focus on technical issues complemented by some code changes. It is often hard to say if a more general discussion I am starting is offtopic to a particular code change or not.

Also, many opened high-level threads create a noise so you cannot longer see what technical work is being done.

So, this is my +1 for a separate place to discuss things.

I am used to both Slack channels and mailing lists. But mailing lists are more serious with good support of history.

**Comment by sebhub** [comment]
Github issues are for issues (problems, features) and keeping the count low is usually good for a project. I don't have time to follow synchronous channels such as IRC, slack. I would like to use something asynchronous, e.g. a mailing list or a forum. Google groups offer both interfaces. A classic mailing list is also an option which @devcurmudgeon offered. It should be archived, long term available and visible to search engines. My proposal is to open a Google group.

**Comment by MartyLake** [comment]
I understand the need to separate issues to discussion, thanks for clarifying.

For me, as an async lurker monitoring the state of the project, I would enjoy if separate discussion stays async, and visible to search engines as well.

**Comment by stanislaw** [comment]
@sebhub if you start the Google group, I would be happy to open my first discussion topic there.

**Comment by sebhub** [comment]
I added a Google group today:

https://groups.google.com/forum/#!forum/doorstop-dev
