### ISSUE TITLE
Test failures on development branch

### ISSUE THREAD

**Issue by sebhub** [doorstop-dev/doorstop#424]
I get two test suite failures with on the development branch 28eb8c135d058f57e5610e7fae031b710d7c156a:

[error.log](https://github.com/doorstop-dev/doorstop/files/3691703/error.log)

**Comment by jacebrowning** [comment]
All tests are passing on CI: https://travis-ci.org/doorstop-dev/doorstop/jobs/592671181

Maybe something is wrong with your environment?

**Comment by stanislaw** [comment]
@sebhub can you always reproduce it? Or it's a flaky test?

I cannot prove it but I think I have seen something similar to happen randomly but very rarely.

**Comment by sebhub** [comment]
It seems to be a bit non-deterministic. I will try to figure out what cases the problem on my machine. I did a fresh clone to make sure everything is up to date.

**Comment by sebhub** [comment]
I think this is somehow related to the inline PlantUML in text attributes. I have changes like this:
```
fill="none" id="Author-&gt;Create Document" style="stroke: #A80036;
fill="none" id="Author-Create Document" style="stroke: #A80036; str
```
In the text source `doorstop/core/tests/files/REQ002.yml`:
  ```plantuml format="svg_inline" alt="Use Cases of Doorstop" title="Use Cases of Doorstop"
  @startuml
  Author --> (Create Document)
  Author --> (Create Item)
  Author --> (Link Item to Document)
  Author --> (Link Item to other Item)
  Author --> (Edit Item)
  Author --> (Review Item)
  Author -> (Delete Item)
  Author -> (Delete Document)
  (Export) <- (Author)
  (Import) <- (Author)
  Reviewer --> (Review Item)
  System --> (Suspect Changes)
  System --> (Integrity)
  @enduml
  ```
Somehow the `>` character is treated differently.

**Comment by henrik-garbergs** [comment]
I have a similar error in the generated HTML code from PlantUML when I run "make ci". This is what doorstop/core/tests/test_all.py::test_lines_html_document_without_child_links expects:
`<p><svg alt="Use Cases of Doorstop" ... height="253px" ...`
And this is what is generated by my unmodified Doorstop code:
`<p><svg alt="Use Cases of Doorstop" ... height="251px" ...`
I removed text at "..." to make it readable above. There are several minor differences in the svg tag from PlantUML on the same line and they are all small number changes.
I'm using the Doorstop code "2.0.post2" from 1 Dec 2019.

If the generated code from PlantUML isn't deterministic enough, maybe we could change the test to look for the svg tag without specifying all the details within the tag? We could for example use a regex in the test to change
`<svg alt="Use Cases of Doorstop" ... ></svg>`
to just
`<svg alt="Use Cases of Doorstop"></svg>`
in both the expected and the generated HTML and then do the comparison between them.

**Comment by jacebrowning** [comment]
I think this is fixed by https://github.com/doorstop-dev/doorstop/pull/483
