### ISSUE TITLE
"ERROR: multiple root documents" error message is not informative enough

### ISSUE THREAD

**Issue by stanislaw** [doorstop-dev/doorstop#432]
It would be great if the error message `ERROR: multiple root documents` would also indicate which root documents/paths are in conflict.

**Comment by sebhub** [comment]
Yes, this error message was quite confusing the first time I saw it. It is not immediately obvious that you can have only one root document per repository. You have to use special options to use multiple root documents.

**Comment by stanislaw** [comment]
Closed via #437.
