### ISSUE TITLE
Getting error "Multiple Root documents"

### ISSUE THREAD

**Issue by manojmsrit** [doorstop-dev/doorstop#436]
Below is the output for the "doorstop -v" command.

(base) MANOJs-MacBook-Air:doorstop manojdeshpande$ doorstop -v
looking for documents in /Users/manojdeshpande...
found document: SRD
found document: SRD
found document: HLTC.txt
found document: HLTC
found document: REQ
found document: TUT
found document: LLT
found document: HLT
found document: SRD
found document: TST
building tree...
root of the tree: SRD
root of the tree: SRD
ERROR: multiple root documents

How to delete the documents and re create new one's

(base) MANOJs-MacBook-Air:doorstop manojdeshpande$ doorstop create MNQ --parent SRD .
building tree...
ERROR: multiple root documents

(base) MANOJs-MacBook-Air:doorstop manojdeshpande$ doorstop delete SRD
building tree...
ERROR: multiple root documents

**Comment by JustinW80** [comment]
It looks like you have some duplicate documents. Search your repository for all the instances of `.doorstop.yml`. For the multiple SRD roots, you'll find two `.doorstop.yml` files with 

```
settings:
  digits: 3
  prefix: SRD
  sep: ''
```

Reconcile and keep only one folder.

It looks like `HTLC.txt` and `HLTC` may also be duplicates.

Maybe you made some errors entering `doorstop create --parent PARENTDOC NEWDOC ./path/to/new/document` commands? See the [docs on creating child documents](https://doorstop.readthedocs.io/en/latest/cli/creation/#child-documents).

**Comment by tangoalx** [comment]
For me it happens when I create a virtual environment with python in the same root directory of the doorstop project. Moving the virtual environment directory upwards solves it. It's because doorstop is delivered with an example project.

**Comment by neerdoc** [comment]
@manojmsrit feel free to close this issue if you feel that your question has been answered!
