### ISSUE TITLE
Rendering of Requirements Headers

### ISSUE THREAD

**Issue by Spenser309** [doorstop-dev/doorstop#447]
Per https://doorstop.readthedocs.io/en/latest/reference/item/ 

I would expect 

```
active: true
derived: false
header: |
  Project Management
level: 1.0
links: []
normative: false
ref: ''
reviewed: null
text: |
  The purpose of the Project Management Process is to identify, establish, and control the activities and resources necessary for a project to produce a product, in the context of the project's requirements and constraints.
```

To be rendered as 

<img width="1081" alt="Screen Shot 2020-01-07 at 9 39 36 AM" src="https://user-images.githubusercontent.com/50548/71915942-ad5e0500-3131-11ea-847e-a2a6bdd16d3b.png">

But instead it's rendered as 

<img width="1083" alt="Screen Shot 2020-01-07 at 9 40 37 AM" src="https://user-images.githubusercontent.com/50548/71915988-c797e300-3131-11ea-893d-b25526776e71.png">

**Comment by JustinW80** [comment]
_Headers_ ([docs link](https://doorstop.readthedocs.io/en/latest/reference/item/#header)) are different from _headings_ ([docs link](https://doorstop.readthedocs.io/en/latest/reference/item/#example-heading)).

Headers are optional, basically a summary short text or slug for the item. They really only make sense for a leaf item (those whose level ends in nonzero).

For your example, you probable want to have an item with level 1.0 and text set to "Project Management", then a separate item with level 1.1 and text set to "The purpose of the...".

Any item whose level ends in .0 is rendered as a heading in published output.

**Comment by Spenser309** [comment]
Thank you for the information! I missed it in my initial read through of the docs.
