### ISSUE TITLE
Several root documents in the same repository?

### ISSUE THREAD

**Issue by henrik-garbergs** [doorstop-dev/doorstop#448]
Hi!

We're considering to use Doorstop at my company for requirement management and I see that you cannot create more than one root document per repository. We are several teams working in the same repository with different SW components. Is it possible for these teams to have their own set of requirements somehow? I suppose it could be solved if all teams have the same root document, but is it possible to do it in another way? It would be nice if the teams could work with requirements independently of each other.

Best regards
Henrik

**Comment by jacebrowning** [comment]
You should be able to create a `.mockvcs` file in each of the "virtual" roots within your monorepo.

https://github.com/doorstop-dev/doorstop/blob/5a074ad3918216e8cd956464119092b330612f87/doorstop/core/vcs/mockvcs.py

The downside to this approach is that Doorstop will not be able to interact with your version control system automatically.

**Comment by henrik-garbergs** [comment]
Yes, you are right. This solves the problem! I added the .mockvcs file to the root directories and included the python code from your link in each file, and now I can create separate sets of requirements in each directory. 
And as you say, Doorstop is no longer automatically adding the created YAML files to git.

**Comment by jacebrowning** [comment]
You might also try creating a `.git` file instead. If that confuses Git, we may need another repository type  (e.g. `.subgit`) for better monorepo support.
