### ISSUE TITLE
Update tests to run on Windows

### ISSUE THREAD

**Issue by jacebrowning** [doorstop-dev/doorstop#452]
Windows testing was added to the CI suite in https://github.com/doorstop-dev/doorstop/pull/451.

Having these tests pass is not yet a required check to merge PRs, but should be. If anyone has a Windows machine or knowledge of operating system differences please help update the tests so we can make this check required.

**Comment by stanislaw** [comment]
@jacebrowning it is clear from the just merged #449 that the CI now fails on Windows. Looks like any other PRs will fail Windows CI until this issue is resolved. 

I could work on this issue but I cannot promise if I can get to it very soon (probably next weekend).

**Comment by bfueldner** [comment]
@stanislaw I guess the tests fail because of the latin-1 codepage python uses on windows environment as default. As a solution the environment variable `PYTHONUTF8=1` has to be set. I found no `appveyor.yml` in the repo to test it, so the change has to be done manually.

**Comment by jacebrowning** [comment]
@bfueldner the file is here: https://github.com/doorstop-dev/doorstop/blob/develop/.appveyor.yml

**Comment by jacebrowning** [comment]
Closed by https://github.com/doorstop-dev/doorstop/pull/463
