### ISSUE TITLE
Building Doorstop from source code

### ISSUE THREAD

**Issue by henrik-garbergs** [doorstop-dev/doorstop#454]
Hi!
I'm trying to make a local copy of Doorstop with code changes and I would like to build and test it. When I run "make exe" I get the error message 
`'doorstop/__main__.py' not found`

In the build process there is a file created called Doorstop.spec. In that file it says:
a = Analysis(['doorstop/__main__.py'],
and if I change this to
a = Analysis(['doorstop/cli/main.py'],
and run "make exe" again, I manage to build the Doorstop cli executable. But this doesn't seem to be how it was originally intended. It looks like the "make exe" should build several executables of Doorstop (cli, gui, server) but how do I do this?

This is my initial output from running make exe:

```
poetry run pyi-makespec doorstop/__main__.py --onefile --windowed --name=Doorstop
wrote /home/henrik/projects/doorstop/Doorstop.spec
now run pyinstaller.py to build the executable
# For framework/shared support: https://github.com/yyuu/pyenv/wiki
poetry run pyinstaller Doorstop.spec --noconfirm --clean
26 INFO: PyInstaller: 3.5
26 INFO: Python: 3.6.9
27 INFO: Platform: Linux-5.3.0-28-generic-x86_64-with-Ubuntu-18.04-bionic
28 INFO: UPX is not available.
28 INFO: Removing temporary files and cleaning cache in /home/henrik/.cache/pyinstaller
Traceback (most recent call last):
  File "/home/henrik/projects/doorstop/.venv/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5', 'console_scripts', 'pyinstaller')()
  File "/home/henrik/projects/doorstop/.venv/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/henrik/projects/doorstop/.venv/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/henrik/projects/doorstop/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/henrik/projects/doorstop/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "Doorstop.spec", line 17, in <module>
    noarchive=False)
  File "/home/henrik/projects/doorstop/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 190, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script 'doorstop/__main__.py' not found
```

I'm using the Doorstop source code version "2.0.post2" from 1 Dec 2019.

Best regards
Henrik

**Comment by jacebrowning** [comment]
The `pyi-makespec` and `pyinstaller` commands will need to be repeated for each entry point:

- `doorstop/cli/main.py`
- `doorstop/gui/main.py`
- `doorstop/server/main.py`

To clarify, the `make exe` target is for building a standalone binary. Is that what you're looking for?

`make dist` will produce a source distribution that will be installable by `pip`.

**Comment by henrik-garbergs** [comment]
OK. I made the following line changes locally in the doorstop Makefile, so now "make exe" builds a standalone binary called "doorstop" that lets me experiment with a modified CLI.

`poetry run pyinstaller $(PROJECT).spec --noconfirm --clean`
to
`poetry run pyinstaller doorstop.spec --noconfirm --clean`

`poetry run pyi-makespec $(PACKAGE)/__main__.py --onefile --windowed --name=$(PROJECT)`
to
`poetry run pyi-makespec doorstop/cli/main.py --onefile --windowed --name=doorstop`

So I'm happy with this! But still, shouldn't "make exe" run without errors out-of-the-box? As I wrote above, I got an error message when running "make exe" and that was before I made changes to any files.

**Comment by jacebrowning** [comment]
Yes, feel free to submit a PR with the changes you've made. 😄

**Comment by henrik-garbergs** [comment]
I'm new to pull requests on Github. I'm reading that I must have write permissions to create a branch, or make a fork instead. What do you recommend?

**Comment by henrik-garbergs** [comment]
Here is the PR: https://github.com/doorstop-dev/doorstop/pull/457
