### ISSUE TITLE
Export additional properties

### ISSUE THREAD

**Issue by sevendays** [doorstop-dev/doorstop#455]
My build system exports requirements to Markdown, then converts them to PDF using panda + eisvogel.

My problem is that for ISO26262 development some requirements need additional properties (e.g.: `ASIL`, `safe_state`, `ftti`) which are very easy to add - I just add a column in the Excel spreadsheet.

However these aren't exported in the Markdown file. As a quick hack I put the `ASIL` (it's only one letter) inside the `summary`, so it is displayed. But the safe state and the fault tolerant time are too long to add in the summary.

I propose to add below the requirement text a list of the user-defined requirement attributes+values.

**Comment by robbel** [comment]
@sevendays are you planning to take a crack at this feature?

**Comment by sevendays** [comment]
@robbel Why not. Let's discuss?

I think the result should look like:

> **REQ001**
>
> Selected requirements attributes **shall** be listed in a table after the text.
>
> | Attribute | Value |
> |----|-----|
> | ASIL        | D        |

Maybe a list of `publish`-able atributes defined inside `.doorstop.yml` would enable the trick:

````
settings:
  digits: 3
  prefix: REQ
  sep: ''
attributes:
  defaults:
    ASIL: D
    hidden_attribute: some_default
  publish:
    - ASIL
````

There is a blocking issue: doorstop doesn't like that!

````
ERROR: unexpected attributes configuration 'publish' in: reqs/.doorstop.yml
````

**Comment by patkan** [comment]
Am I right that this issue describes the same as #151?

**Comment by sevendays** [comment]
Yes, it quite looks the same.

Il mar 23 feb 2021, 13:26 Patrick Kanzler <notifications@github.com> ha
scritto:
