### ISSUE TITLE
No check for duplicated document names

### ISSUE THREAD

**Issue by henrik-garbergs** [doorstop-dev/doorstop#460]
At the moment it is possible to create documents with the same name, for example like this:
```
doorstop create REQS ./reqs
doorstop create REQS --parent REQS ./reqs/reqs 
```
Is this allowed on purpose? 

I'm developing requirements and code in parallel with other teams who are doing the same for the same product. It would be possible that two teams both would decide to create a document called for example "diag" or "support" and in that case it could be difficult to differentiate between requirements (items) when everything is published into a common report later.

I see that there has been a discussion here about adding duplicated items in different git branches, but it doesn't seem to cover document names:
https://github.com/doorstop-dev/doorstop/issues/84

For me it would be useful if Doorstop would check the document tree for duplicated names whenever ```doorstop create``` was run, so I'm thinking about adding it in my local copy of Doorstop. Is that something that would be interesting to have in the github version as well?

**Comment by nhartung** [comment]
I'd be interested in the feature. I can't think of a realistic use case for duplicate document names within  the same project.

**Comment by henrik-garbergs** [comment]
Here is a suggestion to how it can be implemented:
https://github.com/doorstop-dev/doorstop/pull/468

**Comment by jacebrowning** [comment]
Closed by https://github.com/doorstop-dev/doorstop/pull/468
