### ISSUE TITLE
Editing item header in GUI

### ISSUE THREAD

**Issue by Entea** [doorstop-dev/doorstop#464]
Hey!
First of all, I'd like to thank the project contributors for this awesome software!

I've been poking around doorstop and noticed that there's no way to edit item headers.
Would be nice if it could be done without going to export/import or direct source editing.

**Comment by Entea** [comment]
I've submitted a PR and hope that it can be merged :)

**Comment by jacebrowning** [comment]
Closed by https://github.com/doorstop-dev/doorstop/pull/465
