### ISSUE TITLE
Option to disable VCS

### ISSUE THREAD

**Issue by fragmuffin** [doorstop-dev/doorstop#467]
I've found `doorstop` useful in creating a hierarchy of results, then building them into a HTML document.
However, I find that VCS just gets in the way.

Workaround when importing doorstop:

```python
import doorstop

class DummyVCS(doorstop.core.vcs.base.BaseWorkingCopy):
    def lock(self, path): pass
    def edit(self, path): pass
    def add(self, path): pass
    def delete(self, path): pass
    def commit(self, message=None): pass

doorstop.core.vcs.load = lambda p: DummyVCS(p)
```

note: this doesn't help for command-line use.

edit: a much better workaround is using a `.mockvcs` file (see comment below)

**Comment by jacebrowning** [comment]
> VCS just gets in the way

Can you clarify what you mean by "gets in the way"? 

You don't have to work inside a VCS-controlled working copy. If `doorstop` sees a `.mockvcs` file, it will bypass all VCS commands:

https://github.com/doorstop-dev/doorstop/blob/12db40e70434bd24a1110062749560737855414d/doorstop/core/vcs/mockvcs.py

**Comment by fragmuffin** [comment]
@jacebrowning : Sorry, that was blunt...
In a git repo...

```
$ tree tests/2-int/report -a
.
├── build.sh
├── .gitignore
├── README.md
├── results
│   └── .doorstop.yml
└── specs
    └── .doorstop.yml

2 directories, 19 files
```

With `.gitignore` containing:

```
# build output
html

# doorstop items
*.yml
!*.doorstop.yml
```

Then my test environment creates a doorstop 2 items per test:

1. specification from `__doc__` strings, and
1. results from logged output during test execution

However, during test execution, the console is inundated with:

```
The following paths are ignored by one of your .gitignore files:
tests/2-int/report/results/ITR001.yml
Use -f if you really want to add them.
```

So I sought a way to remove the warnings. Given I've no need to commit any of them, I did that terrible hack to remove it.

**Workaround**

> You don't have to work inside a VCS-controlled working copy. If doorstop sees a .mockvcs file, it will bypass all VCS commands

```bash
$ touch tests/2-int/.mockvcs
```

ok, that's much cleaner, thank you.

Is there a way to do this per `Document`?

**Comment by jacebrowning** [comment]
You can also create a `.doorstop.skip` file in a directory to tell `doorstop` to ignore it completely.

This is how we skip the test documents: https://github.com/doorstop-dev/doorstop/tree/73456b52e2dbb2ae51172e39336a30a351a0a7c9/doorstop/core/tests/files

**Comment by fragmuffin** [comment]
Thanks @jacebrowning !
