### ISSUE TITLE
Doorstop is not a library

### ISSUE THREAD

**Issue by sebhub** [doorstop-dev/doorstop#471]
My original goal was to use Doorstop for a pre-qualification of the RTEMS real-time operating system according to ECSS standards. For this I have to write hundreds of requirements or more general specification items. I would like to present some issues that popped up during my daily work with Doorstop. Doorstop is primary a requirements management tool. I has some pretty nice features. In particular, I think the file based organization in YAML format forming a directed acyclic graph (DAG) is really the right thing for this domain. However, it turned out that Doorstop is not designed as a library and contains to much policy. This results in a lack of required flexibility I need.

1. Its primary use case is requirements management. So, it has some standard attributes useful in this domain, like derived, header, level, normative, ref, reviewed, and text. However, I want to use it more generally for specification items and these attributes make not always sense. Having them in every item is just overhead and may cause confusion.

2. The links cannot have custom attributes, e.g. role, enabled-by. With link-specific attributes you could have multiple DAGs formed up by the same set of items.

3. Inside a document (directory) items are supposed to have a common type (set of attributes). I would like to store at a hierarchy level also distinct specializations.

4. The verification of the items is quite limited. I need verification with type-based rules.

5. The UIDs in combination with the document hierarchy lead to duplication, e.g. a/b/c/a-b-c-d.yml. You have the path (a/b/c) also in the file name (a-b-c). You cannot have relative UIDs in links (e.g. ../parent-req) . The specification items may contain multiple requirements, e.g. min/max attributes. There is no way to identify them. 

6. The links are ordered by Doorstop alphabetically by UID. For some applications, it would be better to use the order specified by the user. For example, I used specification items for a new build system. Here it is handy if you can express things like this: A is composed of B and C. Build B before C.

I don't want to change anything in Doorstop, I just wanted to share my issues

**Comment by robbel** [comment]
Thanks for sharing @sebhub. I concur also with your point 2, which I think is a big issue. Could you elaborate what you mean with "verification with type-based rules"?

**Comment by sebhub** [comment]
With type based rules for verification I mean that certain items should have a certain set of attributes, that the values of these attributes belong to a certain value range, that attribute values are internally consistent (e.g. min <= max), that links from one item to another follows a rule (e.g. taking link-specific attributes into account), etc.

**Comment by robbel** [comment]
Thanks for the additional clarity @sebhub.

**Comment by sevendays** [comment]
I agree with point 3: it would be nice to define attributes for the requirement set too (e.g.: define regexes to extract variables from a requirement set) inside `.doorstop.yml`.

This way I could define regexes to parse the requirements and get out signal names and such to automatically build a design (cfr. https://github.com/fraunhofer-iem/reqpat )

Other points that I find surprising:

1. No way to publish requirements attributes (then why do I specify them?) https://github.com/doorstop-dev/doorstop/issues/455
1. Traceability to implementation: a requirement in an automotive project has multiple references - the design allocating the requirement and the analysis of the design spawning new requirements are the first example that comes to my mind. I fail to understand why the `references` behaviour specified [here](https://doorstop.readthedocs.io/en/latest/reference/item/#references-new-array-behavior) stops at the first match (then why do I specify a full array?)
1. The GUI. It's the first reason to not use doorstop in a non-software company. https://github.com/doorstop-dev/doorstop/issues/400 I tried to use excel instead https://github.com/doorstop-dev/doorstop/issues/393 but it's too cumbersome to edit markdown+plantuml texts in excel.

**Comment by jacebrowning** [comment]
Thanks for the discussion! https://github.com/strictdoc-project/strictdoc is also worth exploring.
