### ISSUE TITLE
Table of Contents overlaps with content in generated HTML for certain window sizes.

### ISSUE THREAD

**Issue by dapperfu** [doorstop-dev/doorstop#481]
For browser widths [992, 1199] the TOC overlaps with the content:
![image](https://user-images.githubusercontent.com/223258/85421688-b8231f80-b542-11ea-9760-4197840fb58e.png)

@1200px it 'pops' out to the side:
![image](https://user-images.githubusercontent.com/223258/85421884-f3bde980-b542-11ea-848d-7ae5870e6750.png)

@ 991px it is hidden.

**Comment by neerdoc** [comment]
Probably a bootstrap issue, so might be upstream.

**Comment by neerdoc** [comment]
Fixed by #622
