### ISSUE TITLE
Finished documents in lowercase t fail in doorstep-server

### ISSUE THREAD

**Issue by jmvillalba** [doorstop-dev/doorstop#497]
I have noticed that when I create documents of the type 
doorstop create reqSist ./reqSist --parent ET

And then I run doorstop-server this document is not displayed correctly and shows: 
Sorry, the requested URL 'http://127.0.0.1:7867/documents/pruEs' caused an error:

However the path is correct in the browser
http://127.0.0.1:7867/documents/pruEst

Thank you all for this great tool

**Comment by jacebrowning** [comment]
Fixed by https://github.com/doorstop-dev/doorstop/pull/587
