### ISSUE TITLE
publish / export differences

### ISSUE THREAD

**Issue by yoyodyn** [doorstop-dev/doorstop#512]
Is there a function to publish or export the differences between two refs in git as a set of requirements?  Or is that beyond the scope of what Doorstop should be doing?

I'd like to be able to output a set of requirements as changes instead of having to publish the entire set.  I know git diff can be used to get the differences between two refs, but then it's a matter of parsing the output and how to display it.

**Comment by jacebrowning** [comment]
That would be a useful feature, but it's beyond the initial scope of this project.

**Comment by neerdoc** [comment]
@yoyodyn feel free to close this issue if you feel that your question has been answered!
