### ISSUE TITLE
Enable CI for UNIX-based platforms

### ISSUE THREAD

**Issue by jacebrowning** [doorstop-dev/doorstop#523]
Since Travis CI is no longer free for open source projects, we can't rely on it anymore.

**Comment by chrta** [comment]
Using github actions is probably the best option currently:
https://docs.github.com/en/actions/guides/building-and-testing-nodejs-or-python?langId=py

**Comment by stanislaw** [comment]
+1 for GitHub Actions.

I am not the best CI-engineer but I am happy to share my experience here: https://github.com/strictdoc-project/strictdoc/tree/main/.github/workflows.
