### ISSUE TITLE
Question: How can I reference requirements in implementations?

### ISSUE THREAD

**Issue by fkromer** [doorstop-dev/doorstop#529]
As a developer I would like to be able to reference requirements in the implementation of production and test code (e.g. via UID in doxygen/docstring). Is this possible already?

**Comment by jacebrowning** [comment]
Yeah, you can connect requirement items to keywords in code using references: https://doorstop.readthedocs.io/en/latest/reference/item/#references-new-array-behavior

**Comment by neerdoc** [comment]
@fkromer feel free to close this issue if you feel that your question has been answered!
