### ISSUE TITLE
Linking to multiple parent documents

### ISSUE THREAD

**Issue by dpvdv** [doorstop-dev/doorstop#531]
Currently doorstop allows to link a single parent document, but in large projects, linking to multiple higher-level documents makes a lot of sense. E.g. when the constraint requirements (like EMC, safety, etc.) are also defined in a doorstop document, a child requirements document may want to link to high level functional requirements as well as the constraint requirements, without repeating them in a single top-level parent document.

Is this choice made on-purpose, or would there be a possibility to allow multiple parent documents in the future?

**Comment by jacebrowning** [comment]
That choice was made on purpose, see https://github.com/doorstop-dev/doorstop/issues/292.

**Comment by ckolumbus** [comment]
Pleas check comments in #509 for a solution proposal with implementation spike.

**Comment by ckolumbus** [comment]
@dpvdv I've implemented a suggestion ... could you please review #569 to see whether this fits your needs?
