### ISSUE TITLE
Installation through pip is not working properly

### ISSUE THREAD

**Issue by hugormluis** [doorstop-dev/doorstop#532]
When I install Doorstop through `pip install doorstop` the installed code does not match the code on the github repo. I noticed this because my Doorstop was not checking for duplicate names. This check is done on line 220 of the tree.py script on the core folder. This check code is not in the tree.py script that is installed on my computer.

**Comment by jacebrowning** [comment]
What does `doorstop --version` say?

**Comment by hugormluis** [comment]
It says I'm on v2.1.4.

I tested it on a fresh virtual machine and also on my machine by removing the python package and reinstalling it. It says v2.1.4 and the duplicate checking code is not there.

**Comment by jacebrowning** [comment]
Hmm, I'm not sure what to tell you since that code has been around for two years. Can you inspect the `tree.py` file in your `site-packages` directory?

**Comment by hugormluis** [comment]
Yes I have checked my `/home/$USER/.local/lib/python3.8/site-packages/doorstop/core/tree.py` script and it is missing that part of the code. The gihub tree.py script has 668 lines of code and mine only has 660 lines. The missing code corresponds to that "duplicate name verification" that is missing on my doorstop.

Just to confirm, here are the steps I have done to validate the bug/error:
1 - Installed doorstop through `pip install doorstop`, on a fresh virtual machine.
2 - Initialized a new git repo on a directory.
3 - Tried to create two documents with the same name, it lets me create as much as I want.
4 - Deleted the doorstop directory from the `/home/$USER/.local/lib/python3.8/site-packages` directory.
5 - Downloaded doorstop from the github repo, copied the doorstop folder into the  `/home/$USER/.local/lib/python3.8/site-packages` directory.
6 - Created a new git repo on a fresh new directory.
7 - Tried to create two documents with the same name, it does not let me, as it should be.

It is indeed very strange. I do not understand much about pip and github. But what seems to be happening here is that pip is not installing the code that is here on the github repo. Does the pip come here to the github repo and install this code or it goes to another database? If that is the case, maybe that "other" database was changed?

**Comment by jacebrowning** [comment]
I'll make a new release with everything in `develop` since v2.1.4: https://github.com/doorstop-dev/doorstop/pull/533

**Comment by hugormluis** [comment]
Ok, so that means that I will be able to install, through pip, the code that is on this github repo. Correct?

**Comment by jacebrowning** [comment]
Yeah, give this version a try: https://pypi.org/project/doorstop/2.2/

**Comment by JustinW80** [comment]
Since v2.1.4 was the last stable [release on PyPi](https://pypi.org/project/doorstop/#history). when you did `pip install doorstop`, you'd get v2.1.4.

To have gotten the pre-release, you'd have to tell pip specifically to install that one: `pip install doorstop==2.2b5`. But now that 2.2 proper has shipped, this is just good to know for next time.

**Comment by hugormluis** [comment]
Sorry for my late reply. I have tested the new pip package and it is working as intended. Thank you for your time and dedication.
