### ISSUE TITLE
Server tests fails sometimes

### ISSUE THREAD

**Issue by neerdoc** [doorstop-dev/doorstop#555]
I have noticed that the server tests (specifically `test_check` in `doorstop/server/tests/test_all.py`) fails intermittently when run with Actions. I believe it is simply due to very slow runners used so that the 3 second delay in `setUpClass` is not enough all the time.

Potential solutions:
1. Add a "wait-for-alive"-loop in the `setUpClass` so that the tests do not start until the server is up. With a maximum wait/loop time of maybe 30 seconds/10 loops.
2. Just increase the wait time.

My suggestion would be the first since it does not affect  tests on faster computers.

**Comment by jacebrowning** [comment]
> My suggestion would be the first since it does not affect tests on faster computers.

+1
