### ISSUE TITLE
Test duplicated - no difference?

### ISSUE THREAD

**Issue by neerdoc** [doorstop-dev/doorstop#570]
These two tests seems to be doing exactly the same assertion, even though the `doorstop.settings.REFORMAT` setting if `False` in one and `True` in the other. 

I would assume from the names and description of the tests that a _reformat_ of the link should happen in one case and not the other.

[`test_validate_reformat_when_setting_is_set()`](https://github.com/doorstop-dev/doorstop/blob/develop/doorstop/core/tests/test_item_validator.py#L121)
[`test_validate_no_reformat_when_setting_is_not_set()`](https://github.com/doorstop-dev/doorstop/blob/develop/doorstop/core/tests/test_item_validator.py#L140)

**Comment by jacebrowning** [comment]
It's possible one of those cases was added just to increase coverage somewhere in the internals. If you're working on a related feature, feel free to rewrite/combine those tests.
