### ISSUE TITLE
Link to inactive item causes ERROR, not WARNING, when checking Child's link to Parent

### ISSUE THREAD

**Issue by robertberrington** [doorstop-dev/doorstop#575]
Changing a parent item "active=false" causes an ERROR when running `doorstop` to validate when checking the Child's link to the Parent. Documentation says this is a WARNING.

Reference:  https://doorstop.readthedocs.io/en/latest/cli/validation/
```
An item is linked to an inactive item.
```

I have three levels ... Grandparent, Parent, Child. When checking the Grandparent <- Parent to verify all Grandparent items have child (Parent) links, I get a WARNING. When checking Child -> Parent, I get an ERROR.

If the behavior is correct, documentation should say:
```
WARNING:  An item's child link is an inactive item.
ERROR:  An item's parent link is an inactive item.
```

**Comment by jacebrowning** [comment]
I think the behavior is correct and the documentation should reflect this. The rationale is that "upward" links are the responsibility of that item (via ERROR) but it is useful to know that a "downward" link (child) has been marked inactive (via WARNING).
