### ISSUE TITLE
LaTeX publish does not respect nested itemize

### ISSUE THREAD

**Issue by LarryK82** [doorstop-dev/doorstop#581]
Markdown uses indentation to create nested itemizes. The LaTeX Export only creates one
\begin{itemize}...\end{itemize} scope and ignores the indented "*" items

This is caused by the regex searching for "beginning of line followed by * or - or +" and will also affect the creation trigger of \end{itemize} (currently empty line).

Steps to reproduce:
Create a requirement with nested unordered lists and export to HTML and to LaTeX. LaTeX fails (poor Donald E. Knuth will be sad)

`
* asdf
* Abcd
  * xyz
  * QWERTY
`

**Comment by jacebrowning** [comment]
This beta release contains a fix for this issue: https://pypi.org/project/doorstop/3.0b11/ cc @neerdoc

**Comment by neerdoc** [comment]
Fixed by #615
