### ISSUE TITLE
Missing assets folder in published output

### ISSUE THREAD

**Issue by JustinW80** [doorstop-dev/doorstop#589]
Observed on v3.0b8, tested on Windows, macOS, and CentOS.

When I publish to HTML, the output folder contains a templates folder, but no longer contains an assets folder for the style sheets.

The main effect is now viewing HTML published output loses the navigation sidebar and all styling.

## Steps to reproduce:

1. Start with a fresh repo.
2. Create documents and items without using any templates.
3. Enter `doorstop publish -H all output`
4. Open `output` folder.
5. Observe the `assets` folder should exist.
6. View one of the `.html` documents in your browser.

## Expected result: 

An `assets` folder exists in output. The document in the browser should have styled text and a navigation sidebar.

## Observed result

A `templates` folder exists where the `assets` folder should be. The document in the browser is unstyled and missing the navigation sidebar.

## Workaround

Manually rename `templates` to `assets` in the output folder. Then view the documents in the browser.

## Other observations

I think it was first introduced in v3.0b5, possibly from #573 ? I can't quite follow all the templating changes. cc: @neerdoc 

Reverting to v3.0b4, I observed the correct publishing behavior.

**Comment by jacebrowning** [comment]
This beta release contains a fix for this issue: https://pypi.org/project/doorstop/3.0b11/ cc @neerdoc

**Comment by villanella** [comment]
@jacebrowning There is an error in 3.0b12:
```
$ sudo doorstop publish -H all output
building tree...
loading documents...
publishing tree to '/home/username/doorstop/doorstop-rtm/output'...
Traceback (most recent call last):
  File "/usr/bin/doorstop", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/doorstop/cli/main.py", line 177, in main
    success = function(args, os.getcwd(), parser.error)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/doorstop/cli/commands.py", line 567, in run_publish
    published_path = publisher.publish(
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/doorstop/core/publisher.py", line 85, in publish
    common.write_lines(
  File "/usr/lib/python3.11/site-packages/doorstop/common.py", line 189, in write_lines
    for line in lines:
  File "/usr/lib/python3.11/site-packages/doorstop/core/publisher.py", line 121, in publish_lines
    yield from gen(obj, **kwargs)
  File "/usr/lib/python3.11/site-packages/doorstop/core/publishers/html.py", line 293, in lines
    doc_attributes = get_document_attributes(
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/doorstop/core/publishers/base.py", line 323, in get_document_attributes
    if "name" in attribute_defaults["doc"]:
                 ~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'doc'
```
