### ISSUE TITLE
New release with updated dependency openpyxl

### ISSUE THREAD

**Issue by sebastian-bergt** [doorstop-dev/doorstop#638]
Hi,

since my [PR](https://github.com/doorstop-dev/doorstop/pull/636) was approved and merged, is there a chance you could cut a new release, so the PyPi package gets updated, please?

This would simplify my deployment of doorstop tremendously, not having to check out the .git repo.

BR Sebastian

**Comment by neerdoc** [comment]
Pre-released as v3.0b15
