### ISSUE TITLE
Distutils Deprecated and Removed- Python 3.10+

### ISSUE THREAD

**Issue by sfrinaldi** [doorstop-dev/doorstop#657]
Noticed this issue when I happened to not already have setuptools installed and updated to Python 3.12. I believe either the following could be done (_feel free to add to it if there is another option_):

1. Update requirements.txt (_or equivalent_) if distutils is desired to remain.
    - Python Version Supported change **OR**
    - Add setuptools?
3. Update `import distutils` references to equivalent setuptools alternative (_or something else_).

**Comment by abderrahim** [comment]
It seems distutils is only used for `distutils.spawn.find_executable()`, which can be replaced by `shutil.which()`
